/**
 * TURKEY_IL_ILCE
 * 81 il ve ilçeleri. Her ilçe için yaklaşık merkez koordinatı (lat, lng) verilmiştir.
 *
 * ÖNEMLİ / KAYNAK NOTU:
 * Bu veri seti geliştirici (Claude) tarafından genel coğrafi bilgiden derlenmiştir.
 * Canlıya çıkmadan önce TÜİK / İçişleri Bakanlığı MAKS gibi resmi bir kaynakla
 * çapraz doğrulanması ÖNERİLİR. İlçe koordinatları ilçe merkezinin YAKLAŞIK
 * konumudur; hassas navigasyon için kullanılmamalıdır — sadece "bölge merkezi"
 * referansı olarak (manuel il/ilçe seçiminde arama merkezini belirlemek için)
 * kullanılır. Gerçek eczane konumları Overpass/OSM'den koordinat olarak gelir.
 */
const TURKEY_IL_ILCE = {
  "Adana": { lat: 37.0000, lng: 35.3213, ilceler: ["Aladağ","Ceyhan","Çukurova","Feke","İmamoğlu","Karaisalı","Karataş","Kozan","Pozantı","Saimbeyli","Sarıçam","Seyhan","Tufanbeyli","Yumurtalık","Yüreğir"] },
  "Adıyaman": { lat: 37.7648, lng: 38.2786, ilceler: ["Besni","Çelikhan","Gerger","Gölbaşı","Kahta","Merkez","Samsat","Sincik","Tut"] },
  "Afyonkarahisar": { lat: 38.7507, lng: 30.5567, ilceler: ["Başmakçı","Bayat","Bolvadin","Çay","Çobanlar","Dazkırı","Dinar","Emirdağ","Evciler","Hocalar","İhsaniye","İscehisar","Kızılören","Merkez","Sandıklı","Sinanpaşa","Sultandağı","Şuhut"] },
  "Ağrı": { lat: 39.7191, lng: 43.0503, ilceler: ["Diyadin","Doğubayazıt","Eleşkirt","Hamur","Merkez","Patnos","Taşlıçay","Tutak"] },
  "Amasya": { lat: 40.6499, lng: 35.8353, ilceler: ["Göynücek","Gümüşhacıköy","Hamamözü","Merkez","Merzifon","Suluova","Taşova"] },
  "Ankara": { lat: 39.9334, lng: 32.8597, ilceler: ["Akyurt","Altındağ","Ayaş","Bala","Beypazarı","Çamlıdere","Çankaya","Çubuk","Elmadağ","Etimesgut","Evren","Gölbaşı","Güdül","Haymana","Kalecik","Kazan","Keçiören","Kızılcahamam","Mamak","Nallıhan","Polatlı","Pursaklar","Sincan","Şereflikoçhisar","Yenimahalle"] },
  "Antalya": { lat: 36.8969, lng: 30.7133, ilceler: ["Akseki","Aksu","Alanya","Demre","Döşemealtı","Elmalı","Finike","Gazipaşa","Gündoğmuş","İbradı","Kaş","Kemer","Kepez","Keçiborlu","Konyaaltı","Korkuteli","Kumluca","Manavgat","Muratpaşa","Serik"] },
  "Artvin": { lat: 41.1828, lng: 41.8183, ilceler: ["Ardanuç","Arhavi","Borçka","Hopa","Kemalpaşa","Merkez","Murgul","Şavşat","Yusufeli"] },
  "Aydın": { lat: 37.8560, lng: 27.8416, ilceler: ["Bozdoğan","Buharkent","Çine","Didim","Efeler","Germencik","İncirliova","Karacasu","Karpuzlu","Koçarlı","Köşk","Kuşadası","Kuyucak","Nazilli","Söke","Sultanhisar","Yenipazar"] },
  "Balıkesir": { lat: 39.6484, lng: 27.8826, ilceler: ["Altıeylül","Ayvalık","Balya","Bandırma","Bigadiç","Burhaniye","Dursunbey","Edremit","Erdek","Gömeç","Gönen","Havran","İvrindi","Karesi","Kepsut","Manyas","Marmara","Savaştepe","Sındırgı","Susurluk"] },
  "Bilecik": { lat: 40.1451, lng: 29.9799, ilceler: ["Bozüyük","Gölpazarı","İnhisar","Merkez","Osmaneli","Pazaryeri","Söğüt","Yenipazar"] },
  "Bingöl": { lat: 38.8847, lng: 40.4939, ilceler: ["Adaklı","Genç","Karlıova","Kiğı","Merkez","Solhan","Yayladere","Yedisu"] },
  "Bitlis": { lat: 38.4006, lng: 42.1095, ilceler: ["Adilcevaz","Ahlat","Güroymak","Hizan","Merkez","Mutki","Tatvan"] },
  "Bolu": { lat: 40.7392, lng: 31.6089, ilceler: ["Dörtdivan","Gerede","Göynük","Kıbrıscık","Mengen","Merkez","Mudurnu","Seben","Yeniçağa"] },
  "Burdur": { lat: 37.7203, lng: 30.2908, ilceler: ["Ağlasun","Altınyayla","Bucak","Çavdır","Çeltikçi","Gölhisar","Karamanlı","Kemer","Merkez","Tefenni","Yeşilova"] },
  "Bursa": { lat: 40.1826, lng: 29.0665, ilceler: ["Büyükorhan","Gemlik","Gürsu","Harmancık","İnegöl","İznik","Karacabey","Keles","Kestel","Mudanya","Mustafakemalpaşa","Nilüfer","Orhaneli","Orhangazi","Osmangazi","Yenişehir","Yıldırım"] },
  "Çanakkale": { lat: 40.1553, lng: 26.4142, ilceler: ["Ayvacık","Bayramiç","Biga","Bozcaada","Çan","Eceabat","Ezine","Gelibolu","Gökçeada","Lapseki","Merkez","Yenice"] },
  "Çankırı": { lat: 40.6013, lng: 33.6134, ilceler: ["Atkaracalar","Bayramören","Çerkeş","Eldivan","Ilgaz","Kızılırmak","Korgun","Kurşunlu","Merkez","Orta","Şabanözü","Yapraklı"] },
  "Çorum": { lat: 40.5506, lng: 34.9556, ilceler: ["Alaca","Bayat","Boğazkale","Dodurga","İskilip","Kargı","Laçin","Mecitözü","Merkez","Oğuzlar","Ortaköy","Osmancık","Sungurlu","Uğurludağ"] },
  "Denizli": { lat: 37.7765, lng: 29.0864, ilceler: ["Acıpayam","Babadağ","Baklan","Bekilli","Beyağaç","Bozkurt","Buldan","Çal","Çameli","Çardak","Çivril","Güney","Honaz","Kale","Merkezefendi","Pamukkale","Sarayköy","Serinhisar","Tavas"] },
  "Diyarbakır": { lat: 37.9144, lng: 40.2306, ilceler: ["Bağlar","Bismil","Çermik","Çınar","Çüngüş","Dicle","Eğil","Ergani","Hani","Hazro","Kayapınar","Kocaköy","Kulp","Lice","Silvan","Sur","Yenişehir"] },
  "Edirne": { lat: 41.6771, lng: 26.5557, ilceler: ["Enez","Havsa","İpsala","Keşan","Lalapaşa","Meriç","Merkez","Süloğlu","Uzunköprü"] },
  "Elazığ": { lat: 38.6810, lng: 39.2264, ilceler: ["Ağın","Alacakaya","Arıcak","Baskil","Karakoçan","Keban","Kovancılar","Maden","Merkez","Palu","Sivrice"] },
  "Erzincan": { lat: 39.7500, lng: 39.5000, ilceler: ["Çayırlı","İliç","Kemah","Kemaliye","Merkez","Otlukbeli","Refahiye","Tercan","Üzümlü"] },
  "Erzurum": { lat: 39.9000, lng: 41.2700, ilceler: ["Aşkale","Aziziye","Çat","Hınıs","Horasan","İspir","Karaçoban","Karayazı","Köprüköy","Narman","Oltu","Olur","Palandöken","Pasinler","Pazaryolu","Şenkaya","Tekman","Tortum","Uzundere","Yakutiye"] },
  "Eskişehir": { lat: 39.7767, lng: 30.5206, ilceler: ["Alpu","Beylikova","Çifteler","Günyüzü","Han","İnönü","Mahmudiye","Mihalgazi","Mihalıççık","Odunpazarı","Sarıcakaya","Seyitgazi","Sivrihisar","Tepebaşı"] },
  "Gaziantep": { lat: 37.0662, lng: 37.3833, ilceler: ["Araban","İslahiye","Karkamış","Nizip","Nurdağı","Oğuzeli","Şahinbey","Şehitkamil","Yavuzeli"] },
  "Giresun": { lat: 40.9128, lng: 38.3895, ilceler: ["Alucra","Bulancak","Çamoluk","Çanakçı","Dereli","Doğankent","Espiye","Eynesil","Görele","Güce","Keşap","Merkez","Piraziz","Şebinkarahisar","Tirebolu","Yağlıdere"] },
  "Gümüşhane": { lat: 40.4602, lng: 39.4813, ilceler: ["Kelkit","Köse","Kürtün","Merkez","Şiran","Torul"] },
  "Hakkari": { lat: 37.5744, lng: 43.7408, ilceler: ["Çukurca","Derecik","Merkez","Şemdinli","Yüksekova"] },
  "Hatay": { lat: 36.4018, lng: 36.3498, ilceler: ["Altınözü","Antakya","Arsuz","Belen","Defne","Dörtyol","Erzin","Hassa","İskenderun","Kırıkhan","Kumlu","Payas","Reyhanlı","Samandağ","Yayladağı"] },
  "Iğdır": { lat: 39.9167, lng: 44.0333, ilceler: ["Aralık","Karakoyunlu","Merkez","Tuzluca"] },
  "Isparta": { lat: 37.7648, lng: 30.5566, ilceler: ["Aksu","Atabey","Eğirdir","Gelendost","Gönen","Keçiborlu","Merkez","Senirkent","Sütçüler","Şarkikaraağaç","Uluborlu","Yalvaç","Yenişarbademli"] },
  "İstanbul": { lat: 41.0082, lng: 28.9784, ilceler: ["Adalar","Arnavutköy","Ataşehir","Avcılar","Bağcılar","Bahçelievler","Bakırköy","Başakşehir","Bayrampaşa","Beşiktaş","Beykoz","Beylikdüzü","Beyoğlu","Büyükçekmece","Çatalca","Çekmeköy","Esenler","Esenyurt","Eyüpsultan","Fatih","Gaziosmanpaşa","Güngören","Kadıköy","Kağıthane","Kartal","Küçükçekmece","Maltepe","Pendik","Sancaktepe","Sarıyer","Silivri","Sultanbeyli","Sultangazi","Şile","Şişli","Tuzla","Ümraniye","Üsküdar","Zeytinburnu"] },
  "İzmir": { lat: 38.4237, lng: 27.1428, ilceler: ["Aliağa","Balçova","Bayındır","Bayraklı","Bergama","Beydağ","Bornova","Buca","Çeşme","Çiğli","Dikili","Foça","Gaziemir","Güzelbahçe","Karabağlar","Karaburun","Karşıyaka","Kemalpaşa","Kınık","Kiraz","Konak","Menderes","Menemen","Narlıdere","Ödemiş","Seferihisar","Selçuk","Tire","Torbalı","Urla"] },
  "Kahramanmaraş": { lat: 37.5753, lng: 36.9228, ilceler: ["Afşin","Andırın","Çağlayancerit","Dulkadiroğlu","Ekinözü","Elbistan","Göksun","Nurhak","Onikişubat","Pazarcık","Türkoğlu"] },
  "Karabük": { lat: 41.2061, lng: 32.6204, ilceler: ["Eflani","Eskipazar","Merkez","Ovacık","Safranbolu","Yenice"] },
  "Karaman": { lat: 37.1759, lng: 33.2287, ilceler: ["Ayrancı","Başyayla","Ermenek","Kazımkarabekir","Merkez","Sarıveliler"] },
  "Kars": { lat: 40.6013, lng: 43.0975, ilceler: ["Akyaka","Arpaçay","Digor","Kağızman","Merkez","Sarıkamış","Selim","Susuz"] },
  "Kastamonu": { lat: 41.3887, lng: 33.7827, ilceler: ["Abana","Ağlı","Araç","Azdavay","Bozkurt","Cide","Çatalzeytin","Daday","Devrekani","Doğanyurt","Hanönü","İhsangazi","İnebolu","Küre","Merkez","Pınarbaşı","Seydiler","Şenpazar","Taşköprü","Tosya"] },
  "Kayseri": { lat: 38.7312, lng: 35.4787, ilceler: ["Akkışla","Bünyan","Develi","Felahiye","Hacılar","İncesu","Kocasinan","Melikgazi","Özvatan","Pınarbaşı","Sarıoğlan","Sarız","Talas","Tomarza","Yahyalı","Yeşilhisar"] },
  "Kırıkkale": { lat: 39.8468, lng: 33.5153, ilceler: ["Bahşili","Balışeyh","Çelebi","Delice","Karakeçili","Keskin","Merkez","Sulakyurt","Yahşihan"] },
  "Kırklareli": { lat: 41.7333, lng: 27.2167, ilceler: ["Babaeski","Demirköy","Kofçaz","Lüleburgaz","Merkez","Pehlivanköy","Pınarhisar","Vize"] },
  "Kırşehir": { lat: 39.1425, lng: 34.1709, ilceler: ["Akçakent","Akpınar","Boztepe","Çiçekdağı","Kaman","Merkez","Mucur"] },
  "Kilis": { lat: 36.7184, lng: 37.1212, ilceler: ["Elbeyli","Merkez","Musabeyli","Polateli"] },
  "Kocaeli": { lat: 40.8533, lng: 29.8815, ilceler: ["Başiskele","Çayırova","Darıca","Derince","Dilovası","Gebze","Gölcük","İzmit","Kandıra","Karamürsel","Kartepe","Körfez"] },
  "Konya": { lat: 37.8746, lng: 32.4932, ilceler: ["Ahırlı","Akören","Akşehir","Altınekin","Beyşehir","Bozkır","Cihanbeyli","Çeltik","Çumra","Derbent","Doğanhisar","Emirgazi","Ereğli","Güneysınır","Hadim","Halkapınar","Hüyük","Ilgın","Kadınhanı","Karapınar","Karatay","Kulu","Meram","Sarayönü","Selçuklu","Seydişehir","Taşkent","Tuzlukçu","Yalıhüyük","Yunak"] },
  "Kütahya": { lat: 39.4242, lng: 29.9833, ilceler: ["Altıntaş","Aslanapa","Çavdarhisar","Domaniç","Dumlupınar","Emet","Gediz","Hisarcık","Merkez","Pazarlar","Şaphane","Simav","Tavşanlı"] },
  "Malatya": { lat: 38.3552, lng: 38.3095, ilceler: ["Akçadağ","Arapgir","Arguvan","Battalgazi","Darende","Doğanşehir","Doğanyol","Hekimhan","Kale","Kuluncak","Pütürge","Yazıhan","Yeşilyurt"] },
  "Manisa": { lat: 38.6191, lng: 27.4289, ilceler: ["Ahmetli","Akhisar","Alaşehir","Demirci","Gölmarmara","Gördes","Kırkağaç","Köprübaşı","Kula","Salihli","Sarıgöl","Saruhanlı","Selendi","Soma","Şehzadeler","Turgutlu","Yunusemre"] },
  "Mardin": { lat: 37.3212, lng: 40.7245, ilceler: ["Artuklu","Dargeçit","Derik","Kızıltepe","Mazıdağı","Midyat","Nusaybin","Ömerli","Savur","Yeşilli"] },
  "Mersin": { lat: 36.8121, lng: 34.6415, ilceler: ["Akdeniz","Anamur","Aydıncık","Bozyazı","Çamlıyayla","Erdemli","Gülnar","Mezitli","Mut","Silifke","Tarsus","Toroslar","Yenişehir"] },
  "Muğla": { lat: 37.2153, lng: 28.3636, ilceler: ["Bodrum","Dalaman","Datça","Fethiye","Kavaklıdere","Köyceğiz","Marmaris","Menteşe","Milas","Ortaca","Seydikemer","Ula","Yatağan"] },
  "Muş": { lat: 38.9462, lng: 41.7539, ilceler: ["Bulanık","Hasköy","Korkut","Malazgirt","Merkez","Varto"] },
  "Nevşehir": { lat: 38.6939, lng: 34.6857, ilceler: ["Acıgöl","Avanos","Derinkuyu","Gülşehir","Hacıbektaş","Kozaklı","Merkez","Ürgüp"] },
  "Niğde": { lat: 37.9667, lng: 34.6833, ilceler: ["Altunhisar","Bor","Çamardı","Çiftlik","Merkez","Ulukışla"] },
  "Ordu": { lat: 40.9839, lng: 37.8764, ilceler: ["Akkuş","Altınordu","Aybastı","Çamaş","Çatalpınar","Çaybaşı","Fatsa","Gölköy","Gülyalı","Gürgentepe","İkizce","Kabadüz","Kabataş","Korgan","Kumru","Mesudiye","Perşembe","Ulubey","Ünye"] },
  "Osmaniye": { lat: 37.0742, lng: 36.2478, ilceler: ["Bahçe","Düziçi","Hasanbeyli","Kadirli","Merkez","Sumbas","Toprakkale"] },
  "Rize": { lat: 41.0201, lng: 40.5234, ilceler: ["Ardeşen","Çamlıhemşin","Çayeli","Derepazarı","Fındıklı","Güneysu","Hemşin","İkizdere","İyidere","Kalkandere","Merkez","Pazar"] },
  "Sakarya": { lat: 40.6940, lng: 30.4358, ilceler: ["Adapazarı","Akyazı","Arifiye","Erenler","Ferizli","Geyve","Hendek","Karapürçek","Karasu","Kaynarca","Kocaali","Pamukova","Sapanca","Serdivan","Söğütlü","Taraklı"] },
  "Samsun": { lat: 41.2867, lng: 36.3300, ilceler: ["19 Mayıs","Alaçam","Asarcık","Atakum","Ayvacık","Bafra","Canik","Çarşamba","Havza","İlkadım","Kavak","Ladik","Salıpazarı","Tekkeköy","Terme","Vezirköprü","Yakakent"] },
  "Siirt": { lat: 37.9333, lng: 41.9500, ilceler: ["Baykan","Eruh","Kurtalan","Merkez","Pervari","Şirvan","Tillo"] },
  "Sinop": { lat: 42.0231, lng: 35.1531, ilceler: ["Ayancık","Boyabat","Dikmen","Durağan","Erfelek","Gerze","Merkez","Saraydüzü","Türkeli"] },
  "Sivas": { lat: 39.7477, lng: 37.0179, ilceler: ["Akıncılar","Altınyayla","Divriği","Doğanşar","Gemerek","Gölova","Gürün","Hafik","İmranlı","Kangal","Koyulhisar","Merkez","Suşehri","Şarkışla","Ulaş","Yıldızeli","Zara"] },
  "Şanlıurfa": { lat: 37.1591, lng: 38.7969, ilceler: ["Akçakale","Birecik","Bozova","Ceylanpınar","Eyyübiye","Halfeti","Haliliye","Harran","Hilvan","Karaköprü","Siverek","Suruç","Viranşehir"] },
  "Şırnak": { lat: 37.4187, lng: 42.4918, ilceler: ["Beytüşşebap","Cizre","Güçlükonak","İdil","Merkez","Silopi","Uludere"] },
  "Tekirdağ": { lat: 40.9833, lng: 27.5167, ilceler: ["Çerkezköy","Çorlu","Ergene","Hayrabolu","Kapaklı","Malkara","Marmaraereğlisi","Muratlı","Saray","Süleymanpaşa","Şarköy"] },
  "Tokat": { lat: 40.3167, lng: 36.5500, ilceler: ["Almus","Artova","Başçiftlik","Erbaa","Merkez","Niksar","Pazar","Reşadiye","Sulusaray","Turhal","Yeşilyurt","Zile"] },
  "Trabzon": { lat: 41.0027, lng: 39.7168, ilceler: ["Akçaabat","Araklı","Arsin","Beşikdüzü","Çarşıba","Çaykara","Dernekpazarı","Düzköy","Hayrat","Köprübaşı","Maçka","Of","Ortahisar","Sürmene","Şalpazarı","Tonya","Vakfıkebir","Yomra"] },
  "Tunceli": { lat: 39.3074, lng: 39.4388, ilceler: ["Çemişgezek","Hozat","Mazgirt","Merkez","Nazımiye","Ovacık","Pertek","Pülümür"] },
  "Uşak": { lat: 38.6823, lng: 29.4082, ilceler: ["Banaz","Eşme","Karahallı","Merkez","Sivaslı","Ulubey"] },
  "Van": { lat: 38.4891, lng: 43.4089, ilceler: ["Bahçesaray","Başkale","Çaldıran","Çatak","Edremit","Erciş","Gevaş","Gürpınar","İpekyolu","Muradiye","Özalp","Saray","Tuşba"] },
  "Yalova": { lat: 40.6500, lng: 29.2667, ilceler: ["Altınova","Armutlu","Merkez","Çınarcık","Çiftlikköy","Termal"] },
  "Yozgat": { lat: 39.8181, lng: 34.8147, ilceler: ["Akdağmadeni","Aydıncık","Boğazlıyan","Çandır","Çayıralan","Çekerek","Kadışehri","Merkez","Saraykent","Sarıkaya","Sorgun","Şefaatli","Yenifakılı","Yerköy"] },
  "Zonguldak": { lat: 41.4564, lng: 31.7987, ilceler: ["Alaplı","Çaycuma","Devrek","Ereğli","Gökçebey","Kilimli","Kozlu","Merkez"] },
  "Aksaray": { lat: 38.3687, lng: 34.0370, ilceler: ["Ağaçören","Eskil","Gülağaç","Güzelyurt","Merkez","Ortaköy","Sarıyahşi","Sultanhanı"] },
  "Bayburt": { lat: 40.2552, lng: 40.2249, ilceler: ["Aydıntepe","Demirözü","Merkez"] },
  "Batman": { lat: 37.8812, lng: 41.1351, ilceler: ["Beşiri","Gercüş","Hasankeyf","Kozluk","Merkez","Sason"] },
  "Bartın": { lat: 41.6344, lng: 32.3375, ilceler: ["Amasra","Kurucaşile","Merkez","Ulus"] },
  "Ardahan": { lat: 41.1105, lng: 42.7022, ilceler: ["Çıldır","Damal","Göle","Hanak","Merkez","Posof"] },
  "Düzce": { lat: 40.8438, lng: 31.1565, ilceler: ["Akçakoca","Cumayeri","Çilimli","Gölyaka","Gümüşova","Kaynaşlı","Merkez","Yığılca"] }
};

if (typeof module !== "undefined") module.exports = { TURKEY_IL_ILCE };
